"""kb_vector_store

Revision ID: b3fb5b4b02f0
Revises: 6f4b740e5d56
Create Date: 2026-06-14 19:59:11.928041
"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b3fb5b4b02f0'
down_revision: str | None = '6f4b740e5d56'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('knowledge_bases', sa.Column('vector_store', sa.Text(), server_default=sa.text("'pgvector'"), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('knowledge_bases', 'vector_store')
    # ### end Alembic commands ###
