"""learning_lessons_feedback

Revision ID: d8cf47598f15
Revises: 8c427a5a4d8b
Create Date: 2026-06-14 15:28:24.677437
"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd8cf47598f15'
down_revision: str | None = '8c427a5a4d8b'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lessons',
    sa.Column('id', sa.UUID(as_uuid=False), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('tenant_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('agent_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('source_run_id', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('weight', sa.Float(), server_default=sa.text('1'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], name=op.f('lessons_agent_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('lessons_tenant_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('lessons_pkey'))
    )
    op.create_index('lessons_agent_idx', 'lessons', ['agent_id', 'created_at'], unique=False)
    op.add_column('runs', sa.Column('reward', sa.Float(), nullable=True))
    op.add_column('runs', sa.Column('feedback', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('runs', 'feedback')
    op.drop_column('runs', 'reward')
    op.drop_index('lessons_agent_idx', table_name='lessons')
    op.drop_table('lessons')
    # ### end Alembic commands ###
