"""kb_config

Revision ID: 2c9a4d5cfa8d
Revises: 0001_initial
Create Date: 2026-06-14 13:12:42.463577
"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2c9a4d5cfa8d'
down_revision: str | None = '0001_initial'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('knowledge_bases', sa.Column('description', sa.Text(), nullable=True))
    op.add_column('knowledge_bases', sa.Column('retrieval_mode', sa.Text(), server_default=sa.text("'hybrid'"), nullable=False))
    op.add_column('knowledge_bases', sa.Column('embedding_model', sa.Text(), nullable=True))
    op.add_column('knowledge_bases', sa.Column('rerank_model', sa.Text(), nullable=True))
    op.add_column('knowledge_bases', sa.Column('page_index_enabled', sa.Boolean(), server_default=sa.text('true'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('knowledge_bases', 'page_index_enabled')
    op.drop_column('knowledge_bases', 'rerank_model')
    op.drop_column('knowledge_bases', 'embedding_model')
    op.drop_column('knowledge_bases', 'retrieval_mode')
    op.drop_column('knowledge_bases', 'description')
    # ### end Alembic commands ###
