"""document_source_text

Revision ID: 8c427a5a4d8b
Revises: 2c9a4d5cfa8d
Create Date: 2026-06-14 14:56:24.879985
"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8c427a5a4d8b'
down_revision: str | None = '2c9a4d5cfa8d'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('source_text', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('documents', 'source_text')
    # ### end Alembic commands ###
