"""skills

Revision ID: 6f4b740e5d56
Revises: 5d9c292f0a2c
Create Date: 2026-06-14 19:49:40.794673
"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6f4b740e5d56'
down_revision: str | None = '5d9c292f0a2c'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('skills',
    sa.Column('id', sa.UUID(as_uuid=False), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('tenant_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), server_default=sa.text("''"), nullable=False),
    sa.Column('content', sa.Text(), server_default=sa.text("''"), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('skills_tenant_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('skills_pkey'))
    )
    op.create_index('skills_tenant_name_idx', 'skills', ['tenant_id', 'name'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('skills_tenant_name_idx', table_name='skills')
    op.drop_table('skills')
    # ### end Alembic commands ###
