"""Alembic environment — async (asyncpg), driven by veldra_app settings + ORM models.

`target_metadata = Base.metadata` lets `alembic revision --autogenerate` diff the
ORM models against the live database. The URL comes from settings (single source
of truth), so neither alembic.ini nor CI needs it hard-coded.
"""

from __future__ import annotations

import asyncio
from logging.config import fileConfig

from alembic import context
from pgvector.sqlalchemy import Vector
from sqlalchemy import pool
from sqlalchemy.ext.asyncio import create_async_engine
from veldra_app.config import get_settings
from veldra_app.models import Base

config = context.config
if config.config_file_name is not None:
    fileConfig(config.config_file_name)

config.set_main_option("sqlalchemy.url", get_settings().async_database_url)
target_metadata = Base.metadata


def render_item(type_: str, obj: object, autogen_context) -> str | bool:
    """Render pgvector's Vector with an importable prefix in autogenerated migrations.

    Without this, `alembic revision --autogenerate` emits an unqualified/unimportable
    type for chunks.embedding and the generated script raises NameError at apply time.
    """
    if type_ == "type" and isinstance(obj, Vector):
        autogen_context.imports.add("from pgvector.sqlalchemy import Vector")
        return f"Vector({obj.dim})" if obj.dim else "Vector()"
    return False  # fall back to Alembic's default rendering


_CONFIGURE = {"target_metadata": target_metadata, "compare_type": True, "render_item": render_item}


def run_migrations_offline() -> None:
    context.configure(
        url=get_settings().async_database_url,
        literal_binds=True,
        dialect_opts={"paramstyle": "named"},
        **_CONFIGURE,
    )
    with context.begin_transaction():
        context.run_migrations()


def _do_run_migrations(connection) -> None:
    context.configure(connection=connection, **_CONFIGURE)
    with context.begin_transaction():
        context.run_migrations()


async def run_migrations_online() -> None:
    connectable = create_async_engine(get_settings().async_database_url, poolclass=pool.NullPool)
    async with connectable.connect() as connection:
        await connection.run_sync(_do_run_migrations)
    await connectable.dispose()


if context.is_offline_mode():
    run_migrations_offline()
else:
    asyncio.run(run_migrations_online())
